cmake_minimum_required(VERSION 3.5)
project(scorpio_interfaces)

find_package(ament_cmake REQUIRED)
find_package(rosidl_default_generators REQUIRED)
find_package(std_msgs REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(tf2_msgs REQUIRED)

# Generate interfaces using only relative paths
rosidl_generate_interfaces(${PROJECT_NAME}
  "msg/ArucoTag.msg"
  "msg/ArucoTagArray.msg"
  "msg/AutonomyManagerDebug.msg"
  "msg/AutonomyManagerGoalAndLook.msg"
  "msg/AutonomyManagerInstruction.msg"
  "msg/AutonomyManagerInstructionInfo.msg"
  "msg/AutonomyManagerInstructionInfoList.msg"
  "msg/AutonomyManagerInstructionList.msg"
  "msg/AutonomyManagerState.msg"
  "msg/FollowerState.msg"
  "msg/MapperState.msg"
  "msg/AutonomyPathPlannerState.msg"
  "msg/CanFrame.msg"
  "msg/CbEffortLimits.msg"
  "msg/CbHeartbeatStatus.msg"
  "msg/CbHeartbeatStatusArray.msg"
  "msg/CbPid.msg"
  "msg/CbScienceData.msg"
  "msg/CbScienceData2.msg"
  "msg/CbScienceData3.msg"
  "msg/CheckpointState.msg"
  "msg/DetectedObject.msg"
  "msg/DetectedObjectArray.msg"
  "msg/ErrWarn.msg"
  "msg/ErrWarnArray.msg"
  "msg/InterfaceBandwidth.msg"
  "msg/JointData.msg"
  "msg/JointDataArray.msg"
  "msg/MachineResources.msg"
  "msg/ManipulatorPreset.msg"
  "msg/ManipulatorPresetArray.msg"
  "msg/ManipulatorSequence.msg"
  "msg/ManipulatorSequenceArray.msg"
  "msg/Map.msg"
  "msg/MapDetails.msg"
  "msg/MapUpdate.msg"
  "msg/NamedFloat32.msg"
  "msg/NamedString.msg"
  "msg/NamedUint64.msg"
  "msg/NetworkHosts.msg"
  "msg/NetworkHostsCompact.msg"
  "msg/ObrotowaCmd.msg"
  "msg/Resolution.msg"
  "msg/RosnodeStatus.msg"
  "msg/RoverVisualizationShowElement.msg"
  "msg/StatusLED.msg"
  "msg/StringArray.msg"
  "msg/SubsystemsStatus.msg"
  "msg/UbiquitiStatus.msg"
  "msg/UdpSocketDiagnostics.msg"
  "msg/UdpConnectionDiagnostics.msg"
  "msg/UdpBridgeDiagnostics.msg"
  "srv/AutonomyManagerGetInstructionList.srv"
  "srv/AutonomyManagerAppendInstruction.srv"
  "srv/AutonomyManagerSetInstructionList.srv"
  "srv/AutonomyManagerSetState.srv"
  "srv/GetIntraversablePoints.srv"
  "srv/GetMap.srv"
  "srv/CbGetEffortLimits.srv"
  "srv/CbSetEffortLimits.srv"
  "srv/CbGetPid.srv"
  "srv/CbSetPid.srv"
  "srv/CbSetStatusLedColors.srv"
  "srv/CbGetStatusLedColors.srv"
  "srv/DataManagerLookupFloat32.srv"
  "srv/DataManagerLookupTfMessage.srv"
  "srv/DataManagerTfLookup.srv"
  "srv/EncoderGetOffset.srv"
  "srv/EncoderSetOffset.srv"
  "srv/GetErrWarnArray.srv"
  "srv/GetInt16.srv"
  "srv/GetString.srv"
  "srv/MapperSetIntraversablePoints.srv"
  "srv/SetInt16.srv"
  "srv/SetString.srv"
  "srv/RcClassificationControl.srv"
  "srv/SetStringPair.srv"
  "srv/StringToString.srv"
  DEPENDENCIES std_msgs sensor_msgs tf2_msgs
)

ament_package()

